---
driver:
  name: vagrant
  communicator: ssh
  synced_folders:
    - [".", "/kitchen"]
  customize:
    cableconnected1: 'on'
    memory: 3072
    cpus: 3
    # DE needs 3D acceleration to work
    vram: 256
    accelerate3d: 'on'
    accelerate2dvideo: 'on'
    usb: 'on'
    usbxhci: 'on'

provisioner:
  name: shell
  command: "/bin/bash /kitchen/bootstrap.sh"

platforms:
  - name: archlinux
    driver:
      box: archlinux/archlinux
      provider: virtualbox
  - name: windows10
    driver:
      box: test-win10
      synced_folders:
        - [".", "C:\\Windows\\temp\\system-config"]
  - name: ubuntu
    driver:
      box: ubuntu/bionic64
      provider: virtualbox
    provisioner:
      name: ansible_playbook
      roles_path: roles
      ansible_verbose: true
      ansible_verbosity: 3
      ansible_version: latest
      hosts: media-servers
      playbook: media-server.yml
      sudo: true
      additional_ssh_private_keys:
        - ~/.ssh/id_rsa

suites:
  - name: default
