---
driver:
  name: vagrant
  synced_folders:
    - [".", "/tmp/kitchen"]
  customize:
    cableconnected1: 'on'
    memory: 3072
    cpus: 3
    # DE needs 3D acceleration to work
    vram: 256
    graphicscontroller: vboxvga
    accelerate3d: 'on'
    usb: 'on'
    usbehci: 'on'
    
provisioner:
  name: shell
  sudo: false

platforms:
  - name: archlinux
    driver:
      box: archlinux/archlinux

suites:
  - name: default
