---
driver:
  name: vagrant
  synced_folders:
    - [".", "/tmp/kitchen"]
  customize:
    cableconnected1: 'on'

provisioner:
  name: shell
  sudo: false

platforms:
  - name: archlinux
    driver:
      box: archlinux/archlinux

suites:
  - name: default
    run_list:
    attributes:

