---
# Arch specific tasks
- debug: msg="Running Arch Linux System Configuration Synchronization"

- name: Update pacman Cache
  pacman:
    update_cache: yes
    upgrade: yes

# - name: Install reflector
#   pacman:
#     name: reflector
#     state: latest

# - name: Run reflector
#   command: reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist
#   become: yes
#   become_method: sudo

- name: Install Linux and tools
  pacman:
    name:
      - linux
      - linux-headers
      - base-devel
      - clamav
      - coreutils
      - dhcpcd
      - e2fsprogs
      - efibootmgr
      - exfat-utils
      - grub
      - htop
      - iproute2
      - iputils
      - less
      - lvm2
      - neovim
      - ntfs-3g
      - openssh
      - reflector
      - util-linux
      - zsh
    state: latest

- name: Install Dev Packages
  pacman:
    name:
      - docker
      - go
      - python
      - python-pip
      - ruby
      - git
    state: latest

- name: Create AUR Manager
  user:
    name: aurman
    comment: "AUR Manager"
    shell: /bin/nologin
    home: /home/aurman
    append: yes

- name: Set AUR Manager permissions
  lineinfile:
    path: /etc/sudoers.d/11-install-aurman
    line: 'aurman ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- stat: path=/home/aurman/aur/yay
  register: yay

- name: Clone Yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/aurman/aur/yay
    accept_hostkey: yes
  become: yes
  become_user: aurman
  when: yay.stat.exists == False

- name: Build Yay
  command: chdir=/home/aurman/aur/yay makepkg --cleanbuild --nodeps --force
  become: yes
  become_user: aurman
  when: yay.stat.exists == False

- name: Install Yay
  shell: chdir=/home/aurman/aur/yay pacman -U --noconfirm $(ls | grep -i -m 1 yay*.pkg.tar.xz)
  become: yes
  become_method: sudo
  when: yay.stat.exists == False

- name: Enable Periodic TRIM
  systemd:
    name: fstrim.timer
    enabled: yes

- name: Don't load Speck/Simon (NSA Crypto)
  kernel_blacklist:
    name: CONFIG_CRYPTO_SPECK
    state: present

- name: Install Other Pacman Packages
  pacman:
    name:
      - arc-gtk-theme
      - arc-kde
      - curl
      - firefox
      - kvantum-qt5
      - kvantum-theme-arc
      - latte-dock
      - papirus-icon-theme
      - python-pip
      - python-pywal
      - python2-pip
      - termite
      - thefuck
      - tmux
      - vagrant
      - variety
      - veracrypt
      - virtualbox
      - virtualbox-host-modules-arch
      - wget
      - yakuake
    state: latest

- name: Create {{ username }}
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
    create_home: yes
    state: present
    groups: "wheel,docker"
    append: yes

- name: Install Git dependencies
  include: roles/System Configuration Sync/tasks/git.yml

- stat: path=/home/aurman/aur/yay
  register: yay

- name: Setup AUR
  include: roles/System Configuration Sync/tasks/aur.yml
  retries: 3
  delay: 1
  register: result
  until: result.failed == False

- name: Install Gaming Software
  include: roles/System Configuration Sync/tasks/gaming.yml
  tags:
    - gaming

- stat: "path=/home/{{ username }}/.yadm/repo.git"
  register: dotfiles

- name: Pull Down dotfiles
  command: yadm clone https://github.com/kevinjpickard/dotfiles.git
  become: yes
  become_user: "{{ username }}"
  when: dotfiles.stat.exists == False

- name: Enable vmware-networks service
  systemd:
    name: vmware-networks
    enabled: yes
