# Common tools from github repos
- debug: msg="Installing FOSS tools"

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ homedir }}/.oh-my-zsh"
  become: yes
  become_user: "{{ username }}"

- name: Install Tmux Package Manager
  git: 
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ homedir }}/.tmux/plugins/tpm"
    force: yes
  become: yes
  become_user: "{{ username }}"

- name: Create Dein Folder structure
  file:
    path: "{{ homedir }}/.confg/nvim"
    state: directory
    owner: "{{ username }}"

- name: Install Dein
  get_url: 
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: "{{ homedir }}/installer.sh"
    force: yes
    mode: +x
    owner: "{{ username }}"

- name: Install Dein
  command: "sh {{ homedir }}/installer.sh {{ homedir }}/.config/nvim/dein"
  become: yes
  become_user: "{{ username }}"

- name: Remove Installer
  file: 
    path: "{{ homedir }}/installer.sh"
    state: absent

