---
# Setting up Arch Gaming Packages
- debug: msg="Setting up Arch gaming packages"

- name: Install Pacman Packages
  pacman:
    name: steam
    state: latest

- name: Install AUR Packages
  aur:
    use: yay
    name:
      # broken - discord
      - steam-fonts
      - xpad-dkms-git
  become: yes
  become_user: aurman
