# Linux Specific Tasks
- name: Setting hostname
  hostname: 
    name: "{{ hostname }}"
  when: hostname is defined

- name: Set timezone to America/Denver
  timezone:
    name: America/Denver

- name: Give wheel sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
