- name: Install all my shit
  homebrew:
    name: 
      - amazon-ecs-cli
      - antigen
      - atool
      - autoconf
      - automake
      - avrdude
      - awscli
      - bash-completion
      - boost
      - c-ares
      - cookiecutter
      - coreutils
      - dbus
      - fzf
      - gdbm
      - geoip
      - gettext
      - git
      - glib
      - gmp
      - gnutls
      - go
      - hiredis
      - hub
      - iproute2mac
      - libelf
      - libevent
      - libffi
      - libftdi0
      - libgcrypt
      - libgpg-error
      - libksba
      - libtasn1
      - libtool
      - libusb
      - libusb-compat
      - libxml2
      - libxslt
      - libyaml
      - lua
      - makedepend
      - maven
      - memcached
      - mercurial
      - mongodb
      - mysql
      - nettle
      - neovim
      - nim
      - nmap
      - node
      - nvm
      - openssl
      - ossp-uuid
      - packer
      - pcre
      - pkg-config
      - postgresql
      - pyenv
      - pyenv-virtualenv
      - pyenv-virtualenvwrapper
      - python
      - python3
      - qt5
      - ragel
      - rbenv
      - readline
      - redis
      - ruby-build
      - sqlite
      - subversion
      - task
      - terminal-notifier
      - thefuck
      - tree
      - v8
      - vim
      - watch
      - watchman
      - wget
      - wireshark
      - xz
      - z
      - zookeeper
      - zsh
      - zsh-completion
    state: latest
  become: yes
  become_user: "{{ username }}"

- name: Install Casks
  homebrew:
    name:
      - 1password
      - atom
      - bartender
      - colloquy
      - dash
      - docker
      - evernote
      - firefox
      - flux
      - flycut
      - google-chrome
      - google-cloud-sdk
      - hammerspoon
      - istat-menus
      - iterm2
      - keybase
      - kindle
      - kitematic
      - logitech-options
      - miniconda
      - paw
      - postgres
      - rescuetime
      - robo-3t
      - screenhero
      - sequel-pro
      - slack
      - spotify
      - sublime-text
      - transmit
      - tunnelblick
      - vagrant
      - vienna
      - visual-studio-code
      - virtualbox
      - vlc
      - vmware-fusion
      - wireshark-chmodbpf
      - font-inconsolata
    state: latest
  become: yes
  become_user: "{{ username }}"

- name: Clone dotfiles
  command: yadm clone https://github.com/kevinjpickard/dotfiles.git
  become: yes
  become_user: "{{ username }}"

