---
# Tasks for all Hosts
- debug: msg="Running on Windows"
  when: ansible_kernel is search('Microsoft')

- debug: msg="Detected OS as {{ ansible_distribution }}"

- fail: msg="Username not defined"
  when: username is not defined

- debug: msg="Username is {{ username }}"
  when: username is defined

- stat: path=/home/aurman/aur/yay
  register: yay

- name: Setting hostname
  hostname: 
    name: "{{ hostname }}"
  when: hostname is defined

- name: Set timezone to America/Denver
  timezone:
    name: America/Denver

- name: Run OS Specific Tasks
  include: "{{ ansible_distribution }}.yml"
