---
# Arch specific tasks
- debug: msg="Running Arch Linux System Configuration Setup"

#- name: Update pacman Cache
#  pacman:
#    update_cache: yes
#    upgrade: yes

- name: Install reflector
  pacman:
    name: reflector
    state: latest

- name: Run reflector
  command: reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist
  become: yes
  become_method: sudo

- name: Install Linux and tools
  pacman:
    name:
      - linux
      - linux-headers
      - base-devel
      - clamav
      - coreutils
      - dhcpcd
      - e2fsprogs
      - efibootmgr
      - exfat-utils
      - grub
      - htop
      - iproute2
      - iputils
      - less
      - lvm2
      - neovim
      - ntfs-3g
      - openssh
      - reflector
      - util-linux
      - zsh
    state: latest

- name: Install Intel Microcode
  pacman:
    name: intel-ucode
    state: latest
  when: ansible_processor is superset(["GenuineIntel"])
  register: intel

- name: Modify Grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
    state: present

- command: blkid -o value -s UUID /dev/nvme0n1p3
  register: uuid

- name: Modify Grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="luks.name={{ uuid.stdout }}=cryptroot root=/dev/vg0/root"'
    state: present

- name: Modify Grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_PRELOAD_MODULES='
    line: 'GRUB_PRELOAD_MODULES="lvm part_gpt part_msdos"'
    state: present

- name: Modify mkinitcpio modules
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES=(ext4)'
    state: present

- name: Modify mkinitcpio hooks
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: 'HOOKS=(base udev autodetect modconf block systemd sd-encrypt sd-lvm2 filesystems keyboard fsck)'
    state: present

- name: mkinitcpio
  command: mkinitcpio -p linux
  become: yes
  become_method: sudo

- name: Regenerate GRUB Config to enable Intel Microcode Updates
  command: grub-mkconfig -o /boot/grub/grub.cfg
  become: yes
  become_method: sudo
  when: intel is defined

- name: Install Desktop Environment
  pacman:
    name:
      - i3
      - networkmanager
      - plasma
      - rofi
      - sddm
      - xorg
    state: latest

- name: Enable SDDM
  systemd:
    name: sddm
    enabled: yes

- name: Download PIA
  get_url:
    url: https://www.privateinternetaccess.com/installer/x/download_installer_linux
    dest: "/home/{{ username }}/install_pia.run"

- name: Install PIA
  shell: "/home/{{ username }}/install_pia.run"
