---
# tasks file for arch
- name: Update pacman Cache
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install pacman scripts and tools
  pacman:
    name: pacman-contrib
    state: latest

- stat: path=/etc/pacman.d/mirrorlist.orig
  register: backup

- name: Backup Mirrors
  command: mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig
  become: yes
  become_method: sudo
  when: backup.stat.exists == False

- stat: path=/etc/pacman.d/mirrorlist
  register: ranked

- name: Rank Mirrors
  shell: rankmirrors /etc/pacman.d/mirrorlist.orig > /etc/pacman.d/mirrorlist
  become: yes
  become_method: sudo
  when: ranked.stat.exists == False

- name: Install Kernel
  pacman:
    name: linux
    state: latest
    
- name: Install Kernel Headers
  pacman:
    name: linux-headers
    state: latest
    
- name: Install Base Development Packages
  pacman:
    name: base-devel
    state: latest
    
- name: Install Neovim
  pacman:
    name: neovim
    state: latest
    
- name: Install git
  pacman:
    name: git
    state: latest
    
- name: Install DHCP Tools
  pacman:
    name: dhcpcd
    state: latest
    
- name: Install GRUB
  pacman:
    name: grub
    state: latest
    
- name: Install Boot Manager
  pacman:
    name: efibootmgr
    state: latest
    
- name: Install ExFAT Utilities
  pacman:
    name: exfat-utils
    state: latest
    
- name: Install NTFS Driver
  pacman:
    name: ntfs-3g
    state: latest
    
- name: Install OpenSSH
  pacman:
    name: openssh
    state: latest
    
- name: Install CoreUtils
  pacman:
    name: coreutils
    state: latest
    
- name: Install e2fsprogs
  pacman:
    name: e2fsprogs
    state: latest
    
- name: Install lvm2
  pacman:
    name: lvm2
    state: latest
    
- name: Install Intel Microcode
  pacman:
    name: intel-ucode
    state: latest
    
- name: Install less
  pacman:
    name: less
    state: latest
    
- name: Install iproute2
  pacman:
    name: iproute2
    state: latest
    
- name: Install iputils
  pacman:
    name: iputils
    state: latest
    
- file:
    path: "{{home}}/Documents/github/scratch"
    state: directory
  become: true
  become_method: sudo
  become_user: "{{account}}"

- name: Clone Yay
  git:
    repo: https://github.com/Jguer/yay.git
    dest: ~/Documents/github/scratch/yay
    clone: yes

- name: Compile and Install Yay
  command: makepkg -si
  chdir: ~/Documents/github/scratch/yay

