---
# Tasks for all Hosts
- debug: msg="Detected OS as {{ ansible_distribution }}"

- name: Setting hostname
  hostname: 
    name: "{{ hostname }}"
  when: hostname is defined

- fail: msg="Username/password not specified, please specify, i.e. --extra-vars 'username=<username> password=<password>'"
  when: username is undefined

- fail: msg="Username/password not specified, please specify, i.e. --extra-vars 'username=<username> password=<password>'"
  when: password is undefined

- name: Set timezone to America/Denver
  timezone:
    name: America/Denver

- name: Run OS Specific Tasks
  include: "{{ ansible_distribution }}.yml"
