- name: "Setup {{ username }}"
  user:
    name: "{{ username }}"
    shell: /bin/zsh
    groups: admin
    append: yes

- name: Install Java cuz otherwise some brew installs fail
  homebrew_cask:
    name: java
    state: latest
  become: yes
  become_user: "{{ username }}"

- name: HomeBrew Taps
  homebrew_tap:
    name: "{{ item }}"
  with_items:
    - cjbassi/gotop
    - mongodb/brew
  ignore_errors: yes

- name: Pour Kegs
  homebrew:
    name: ['amazon-ecs-cli',
          'antigen',
          'awscli',
          'bash-completion',
          'coreutils',
          'git',
          'glib',
          'gmp',
          'gnutls',
          'go',
          'gotop',
          'htop',
          'iproute2mac',
          'jq',
          'libelf',
          'libevent',
          'libffi',
          'libftdi0',
          'libgcrypt',
          'libgpg-error',
          'libksba',
          'libtasn1',
          'libtool',
          'libusb',
          'libusb-compat',
          'libxml2',
          'libxslt',
          'libyaml',
          'lua',
          'makedepend',
          'memcached',
          'mercurial',
          'mongodb-community',
          'mysql',
          'neofetch',
          'neovim',
          'nmap',
          'node',
          'nvm',
          'openssl',
          'osquery',
          'packer',
          'pkg-config',
          'postgresql',
          'pyenv',
          'pyenv-virtualenv',
          'pyenv-virtualenvwrapper',
          'python',
          'python3',
          'qt5',
          'rbenv',
          'readline',
          'redis',
          'ruby-build',
          'sqlite',
          'subversion',
          'terminal-notifier',
          'thefuck',
          'tmux',
          'tree',
          'watch',
          'wget',
          'wireshark',
          'yadm',
          'zsh',
          'zsh-completion']
  become: yes
  become_user: "{{ username }}"
  environment:
    SUDO_ASKPASS: "{{ ansible_sudo_pass }}"

- name: install casks
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items:
    - 1password
    - atom
    - bartender
    - colloquy
    - dash
    - docker
    - dotnet-sdk
    - evernote
    - firefox
    - flux
    - flycut
    - google-chrome
    - google-cloud-sdk
    - hammerspoon
    - istat-menus
    - iterm2
    - keybase
    - kindle
    - kitematic
    - logitech-options
    - miniconda
    - paw
    - postgres
    - rescuetime
    - robo-3t
    - screenhero
    - sequel-pro
    - slack
    - spotify
    - sublime-text
    - transmit
    - tunnelblick
    - vagrant
    - vagrant-vmware-utility
    - vienna
    - visual-studio-code
    - vlc
    - vmware-fusion
    - wireshark-chmodbpf
    - font-inconsolata
  environment:
    SUDO_ASKPASS: "{{ ansible_sudo_pass }}"
  become: yes
  become_user: "{{ username }}"
  ignore_errors: yes

- name: Install VirtualBox (Will probably report failure cuz mac always blocks the kext)
  homebrew_cask:
    name: virtualbox
    state: latest
  become: yes
  become_user: "{{ username }}"
  ignore_errors: yes
  environment:
    SUDO_ASKPASS: "{{ ansible_sudo_pass }}"

- name: Include git repos
  include: ./roles/System Configuration Sync/tasks/git.yml

- name: Clone dotfiles
  command: yadm clone https://github.com/kevinjpickard/dotfiles.git
  become: yes
  become_user: "{{ username }}"

