---
# System Configuration

- hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: true
  environment:
    ANSIBLE_LIBRARY: ~/sysconfig/library

  roles:
    - System Configuration Sync
